---

- hosts: all
  become: true
  tasks:

  - name: update apk cache
    apk:
      update_cache: yes

  - name: install apache2 package
    apk:
      name: apache2
      state: latest
  
  - name: install php
    apk:
      name: php
      state: latest

  - name: add nodejs
    apk:
      name: 
        - nodejs
        - npm 
      state: latest
    when: ansible_distribution == "Alpine"
  
  - name: add pm2
    npm:
      name: pm2@latest
      global: yes
      state: latest
    when: ansible_distribution == "Alpine"
  
  - name: Debug OS information
    debug:
      msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  
    


