---

- hosts: all
  become: true
  tasks:

  - name: update apk cache
    apk:
      update_cache: yes

  - name: install apache2 package
    apk:
      name: apache2
  
  - name: add nodejs
    apk:
      name: 
        - nodejs
        - npm 
      state: present
     
  
    


